GET http://localhost:3000/api/users/me
x-maid-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Zjc1YWJmNDc2ZjlkZWYyZWUzNjBmYTAiLCJlbWFpbCI6Imh5ZmFuZHJlYUBnbWFpbC5jb20iLCJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MDE2MjEzODgsImV4cCI6MTYwMjIyNjE4OH0.gwN76lKfwI9lEijQz2Ps8-HtFK6oo3HW5jKKypWO6bM